chat_model_name: xopqwen36v35b
embedding_model_name: xop3qwen8bembedding
xf_embedding_base_url: https://maas-api.cn-huabei-1.xf-yun.com/v2
xf_chat_base_url: https://maas-api.cn-huabei-1.xf-yun.com/v2
xf_api_key: 3c3e613858421bbe6ad1f8e8838e3f99:NjI3MWY3MTAxODQ5ZmNlYzBmODljNjIw
